import { rmSync, existsSync, mkdirSync } from "node:fs";
import { analyze, analyzeAudioEnvelope, analyzeAudioPan } from "../../lib/analyze.mjs";
import { newProject } from "../../helpers/app.mjs";
import { driveExport } from "../../helpers/export.mjs";
import { fixture, tmpOut, tmpProjectParent } from "../../helpers/media.mjs";

// ─── Shared project-parent folders ───────────────────────────────────────────
const PROJECT_PARENT_CONFORMANCE = tmpProjectParent("weftcut-e2e-audio-proj");
const PROJECT_PARENT_FORMATS = tmpProjectParent("weftcut-e2e-audiofmt-proj");
const PROJECT_PARENT_ENVELOPE = tmpProjectParent("weftcut-e2e-audio-env-proj");

// ─── Envelope suite: the 30fps tone-marker fixture (shared with conformance) ─
const SOURCE = fixture("test_1080p_30fps_audio.mp4");

// ─── 1. Audio conformance matrix ─────────────────────────────────────────────
// Audio conformance across the matrix: source frame rate (video-grid-vs-audio
// sync) x export container (mux path). Each case imports the matching audio
// source (per-second tone markers F_k = 400 + 120k Hz), exports to the target
// container, and verifies per-second alignment + A/V drift + tone SNR via
// `media_conformance --audio`. Fixtures are generated by onPrepare.
const FPS = [30, 60, 120];
const CONTAINERS = ["mp4", "mkv", "mov"];
const CASES = FPS.flatMap((fps) => CONTAINERS.map((container) => ({ fps, container })));

describe("audio conformance matrix (real WebView2)", function () {
  before(function () {
    mkdirSync(PROJECT_PARENT_CONFORMANCE, { recursive: true });
  });

  for (const c of CASES) {
    const source = fixture(`test_1080p_${c.fps}fps_audio.mp4`);
    const output = tmpOut(`weftcut-e2e-audio-${c.fps}-${c.container}.${c.container}`);

    it(`${c.fps}fps source -> ${c.container} export stays aligned + synced + faithful`, async function () {
      if (!existsSync(source)) {
        console.warn(`[e2e] SKIP: audio source not found at ${source}`);
        this.skip();
      }
      rmSync(output, { force: true });

      await newProject({
        parentFolder: PROJECT_PARENT_CONFORMANCE,
        name: "e2e-audio-" + Date.now(),
        canvas: { width: 1920, height: 1080, fpsNum: 30, fpsDen: 1 },
      });

      const label = `${c.fps}fps/${c.container}`;
      const r = await driveExport(
        { mediaAbsPath: source, outputAbsPath: output, settings: { container: c.container } },
        { label },
      );
      if (!r.done.ok) {
        throw new Error(
          `exportClip failed: ${r.done.error} | exportState kind=${r.lastKind} detail=${r.lastDetail} (last frame=${r.lastFrame})`,
        );
      }

      const report = analyze({ output, source, samples: [0], audio: true });
      console.log(`[e2e] audio report ${c.fps}fps/${c.container}:`, JSON.stringify(report));

      const misaligned = report.samples.filter((s) => !s.aligned);
      if (misaligned.length > 0) {
        throw new Error("audio seconds misaligned: " +
          JSON.stringify(misaligned.map((s) => ({ second: s.second, detected: s.detected_freq }))));
      }
      expect(Math.abs(report.drift_slope - 1)).toBeLessThanOrEqual(0.01);
      expect(Math.abs(report.offset_ms)).toBeLessThanOrEqual(66);
      expect(report.pass).toBe(true);
    });
  }
});

// ─── 2. Audio-only format matrix ─────────────────────────────────────────────
// AUDIO-ONLY sources end-to-end, per format the import dialog offers: import
// (probe + classify as Audio) → conform (ffmpeg → VCONF) → Audio layer →
// audio-only export mix → AAC `.m4a`, verified by `media_conformance --audio`
// against the per-second tone markers (F_k = 400 + 120k Hz) baked into the
// fixtures. The export is audio-only (`includeVideo:false`) because an
// audio-only project has no visible video layer — a video export is correctly
// rejected by the no-material guard (see export_content_modes.e2e.js).
//
// This is the pipeline gate; the FORMAT range itself is pinned cheaply by the
// Rust unit matrix (jobs::conform::tests::conform_format_matrix_*). The mp3
// fixture carries embedded attached_pic cover art — the real-world mp3 shape
// that used to misclassify as Video (probe::detect_kind regression): if that
// regresses, the placed layer is a VideoClip whose proxy can never land and
// the export-ready wait times out loudly.
const FORMATS = ["wav", "mp3", "flac", "m4a", "ogg"];

describe("audio-only format matrix (real WebView2)", function () {
  before(function () {
    mkdirSync(PROJECT_PARENT_FORMATS, { recursive: true });
  });

  for (const fmt of FORMATS) {
    const source = fixture(`test_tones_10s.${fmt}`);
    const output = tmpOut(`weftcut-e2e-audiofmt-${fmt}.m4a`);

    it(`${fmt} source -> audio export stays aligned + faithful`, async function () {
      if (!existsSync(source)) {
        console.warn(`[e2e] SKIP: audio source not found at ${source}`);
        this.skip();
      }
      rmSync(output, { force: true });

      await newProject({
        parentFolder: PROJECT_PARENT_FORMATS,
        name: `e2e-audiofmt-${fmt}-` + Date.now(),
        canvas: { width: 1920, height: 1080, fpsNum: 30, fpsDen: 1 },
      });

      const r = await driveExport(
        {
          mediaAbsPath: source,
          outputAbsPath: output,
          settings: { includeVideo: false, includeAudio: true },
        },
        { timeout: 150000 },
      );
      if (!r.done.ok) {
        throw new Error(
          `exportClip failed: ${r.done.error} | exportState kind=${r.lastKind} detail=${r.lastDetail}`,
        );
      }

      const report = analyze({ output, source, samples: [0], audio: true });
      console.log(`[e2e] audio-only report ${fmt}:`, JSON.stringify(report));

      const misaligned = report.samples.filter((s) => !s.aligned);
      if (misaligned.length > 0) {
        throw new Error("audio seconds misaligned: " +
          JSON.stringify(misaligned.map((s) => ({ second: s.second, detected: s.detected_freq }))));
      }
      expect(Math.abs(report.drift_slope - 1)).toBeLessThanOrEqual(0.01);
      expect(Math.abs(report.offset_ms)).toBeLessThanOrEqual(66);
      expect(report.pass).toBe(true);
    });
  }
});

// ─── 3. Audio envelope conformance ───────────────────────────────────────────
// Audio-engine conformance (docs/audio.md §Testing): the deterministic Rust
// mixer upgrades audio assertions from perceptual (Goertzel tones) to
// ANALYTIC — windowed-RMS envelopes against closed-form expectations, the
// alimiter ceiling, and the equal-power pan law's L/R energy ratio.
//
// Keyframed-gain note: there is no keyframe IPC/hook surface to drive yet,
// so the keyframed-gain case is locked at the math level instead (the
// cross-language envelope goldens + `audio::mix` unit tests); the fade
// scenarios here exercise the same sampled-envelope pipeline end-to-end.

/// Boot a fresh 30fps project and run exportClip with audio patches.
async function bootAndExport({ output, audioPatches, settings }) {
  await newProject({
    parentFolder: PROJECT_PARENT_ENVELOPE,
    name: "e2e-audio-env-" + Date.now(),
    canvas: { width: 1920, height: 1080, fpsNum: 30, fpsDen: 1 },
  });

  const args = { mediaAbsPath: SOURCE, outputAbsPath: output };
  if (audioPatches) args.audioPatches = audioPatches;
  if (settings) args.settings = settings;

  const r = await driveExport(args);
  if (!r.done.ok) {
    throw new Error(
      `exportClip failed: ${r.done.error} | exportState kind=${r.lastKind} detail=${r.lastDetail}`,
    );
  }
}

describe("audio envelope conformance (real WebView2)", function () {
  before(function () {
    if (!existsSync(SOURCE)) {
      console.warn(`[e2e] SKIP suite: source not found at ${SOURCE}`);
      this.skip();
    }
    mkdirSync(PROJECT_PARENT_ENVELOPE, { recursive: true });
  });

  it("fade-in shapes the exported RMS envelope analytically", async function () {
    // 1 s linear fade-in at unity gain: window RMS deltas vs the loudest
    // window are 20·log10(t) — −12.04 dB at 0.25 s, −6.02 at 0.5 s,
    // −2.50 at 0.75 s, 0 in the body. ±1.5 dB bound absorbs AAC + the
    // −1 dB limiter ceiling on a hot fixture.
    const output = tmpOut("weftcut-e2e-fadein.mp4");
    rmSync(output, { force: true });

    await bootAndExport({
      output,
      audioPatches: [{ fade_in_us: 1_000_000 }],
    });

    const report = analyzeAudioEnvelope({
      output,
      expects: [
        { t_s: 0.25, expect_rms_db_delta: -12.04 },
        { t_s: 0.5, expect_rms_db_delta: -6.02 },
        { t_s: 0.75, expect_rms_db_delta: -2.5 },
        { t_s: 5.0, expect_rms_db_delta: 0.0 },
      ],
    });
    console.log("[e2e] fade-in envelope report:", JSON.stringify(report));
    expect(report.pass).toBe(true);
  });

  it("fade-out shapes the tail and static gain offsets the body", async function () {
    // −6 dB static gain + 1 s fade-out on a 10 s clip: the loudest window
    // is the body (the gain is uniform, so deltas are gain-independent);
    // the tail ramps down −6.02 dB at 9.5 s, −12.04 dB at 9.75 s.
    const output = tmpOut("weftcut-e2e-fadeout.mp4");
    rmSync(output, { force: true });

    await bootAndExport({
      output,
      audioPatches: [{ gain_db: -6, fade_out_us: 1_000_000 }],
    });

    const report = analyzeAudioEnvelope({
      output,
      expects: [
        { t_s: 5.0, expect_rms_db_delta: 0.0 },
        { t_s: 9.5, expect_rms_db_delta: -6.02 },
        { t_s: 9.75, expect_rms_db_delta: -12.04 },
      ],
    });
    console.log("[e2e] fade-out envelope report:", JSON.stringify(report));
    expect(report.pass).toBe(true);
  });

  it("two overlapping layers sum and the limiter holds the -1 dB ceiling", async function () {
    // The same clip stacked twice (0 dB + −6 dB). Whatever the fixture's
    // own level, the summed peak must never exceed the alimiter ceiling
    // (−1 dB ≈ −0.9 dBFS with codec slop).
    const output = tmpOut("weftcut-e2e-overlap.mp4");
    rmSync(output, { force: true });

    await bootAndExport({
      output,
      audioPatches: [{}, { gain_db: -6 }],
    });

    const report = analyzeAudioEnvelope({
      output,
      expects: [{ t_s: 5.0, expect_rms_db_delta: 0.0 }],
      peakMaxDb: -0.9,
    });
    console.log("[e2e] overlap+limiter report:", JSON.stringify(report));
    expect(report.peak_ceiling_pass).toBe(true);
    expect(report.pass).toBe(true);
  });

  it("pan -0.8 lands the equal-power L/R energy ratio", async function () {
    // Equal-power law with correlated channels collapses to
    // cot(x·π/2 / 2)… concretely for pan = −0.8: L−R = 20·log10(cot(0.05π))
    // ≈ +16.0 dB. (Mono and stereo inputs agree for identical-channel
    // content — the cross-bleed term makes the stereo law collapse to the
    // mono law's ratio.)
    const output = tmpOut("weftcut-e2e-pan.mp4");
    rmSync(output, { force: true });

    await bootAndExport({
      output,
      audioPatches: [{ pan: -0.8 }],
    });

    const report = analyzeAudioPan({ output, expectLrDb: 16.0 });
    console.log("[e2e] pan report:", JSON.stringify(report));
    expect(report.pass).toBe(true);
  });
});
