import { rmSync, existsSync, mkdirSync } from "node:fs";
import { analyze, analyzeAudioEnvelope, analyzeAudioPan } from "../../lib/analyze.mjs";
import { invokeCmd, newProject, summary, waitForHook } from "../../helpers/app.mjs";
import { driveExport } from "../../helpers/export.mjs";
import { fixture, tmpOut, tmpProjectParent } from "../../helpers/media.mjs";

// ─── Shared project-parent folders ───────────────────────────────────────────
const PROJECT_PARENT_CONFORMANCE = tmpProjectParent("weftcut-e2e-audio-proj");
const PROJECT_PARENT_FORMATS = tmpProjectParent("weftcut-e2e-audiofmt-proj");
const PROJECT_PARENT_ENVELOPE = tmpProjectParent("weftcut-e2e-audio-env-proj");
const PROJECT_PARENT_ROLES = tmpProjectParent("weftcut-e2e-audio-roles-proj");

// ─── Envelope suite: the 30fps tone-marker fixture (shared with conformance) ─
const SOURCE = fixture("test_1080p_30fps_audio.mp4");

// ─── 1. Audio conformance matrix ─────────────────────────────────────────────
// Audio conformance across the matrix: source frame rate (video-grid-vs-audio
// sync) x export container (mux path). Each case imports the matching audio
// source (per-second tone markers F_k = 400 + 120k Hz), exports to the target
// container, and verifies per-second alignment + A/V drift + tone SNR via
// `media_conformance --audio`. Fixtures are generated by onPrepare.
const FPS = [30, 60, 120];
const CONTAINERS = ["mp4", "mkv", "mov"];
const CASES = FPS.flatMap((fps) => CONTAINERS.map((container) => ({ fps, container })));

describe("audio conformance matrix (real WebView2)", function () {
  before(function () {
    mkdirSync(PROJECT_PARENT_CONFORMANCE, { recursive: true });
  });

  for (const c of CASES) {
    const source = fixture(`test_1080p_${c.fps}fps_audio.mp4`);
    const output = tmpOut(`weftcut-e2e-audio-${c.fps}-${c.container}.${c.container}`);

    it(`${c.fps}fps source -> ${c.container} export stays aligned + synced + faithful`, async function () {
      if (!existsSync(source)) {
        console.warn(`[e2e] SKIP: audio source not found at ${source}`);
        this.skip();
      }
      rmSync(output, { force: true });

      await newProject({
        parentFolder: PROJECT_PARENT_CONFORMANCE,
        name: "e2e-audio-" + Date.now(),
        canvas: { width: 1920, height: 1080, fpsNum: 30, fpsDen: 1 },
      });

      const label = `${c.fps}fps/${c.container}`;
      const r = await driveExport(
        { mediaAbsPath: source, outputAbsPath: output, settings: { container: c.container } },
        { label },
      );
      if (!r.done.ok) {
        throw new Error(
          `exportClip failed: ${r.done.error} | exportState kind=${r.lastKind} detail=${r.lastDetail} (last frame=${r.lastFrame})`,
        );
      }

      const report = analyze({ output, source, samples: [0], audio: true });
      console.log(`[e2e] audio report ${c.fps}fps/${c.container}:`, JSON.stringify(report));

      const misaligned = report.samples.filter((s) => !s.aligned);
      if (misaligned.length > 0) {
        throw new Error("audio seconds misaligned: " +
          JSON.stringify(misaligned.map((s) => ({ second: s.second, detected: s.detected_freq }))));
      }
      expect(Math.abs(report.drift_slope - 1)).toBeLessThanOrEqual(0.01);
      expect(Math.abs(report.offset_ms)).toBeLessThanOrEqual(66);
      expect(report.pass).toBe(true);
    });
  }
});

// ─── 2. Audio-only format matrix ─────────────────────────────────────────────
// AUDIO-ONLY sources end-to-end, per format the import dialog offers: import
// (probe + classify as Audio) → conform (ffmpeg → VCONF) → Audio layer →
// audio-only export mix → AAC `.m4a`, verified by `media_conformance --audio`
// against the per-second tone markers (F_k = 400 + 120k Hz) baked into the
// fixtures. The export is audio-only (`includeVideo:false`) because an
// audio-only project has no visible video layer — a video export is correctly
// rejected by the no-material guard (see export_content_modes.e2e.js).
//
// This is the pipeline gate; the FORMAT range itself is pinned cheaply by the
// Rust unit matrix (jobs::conform::tests::conform_format_matrix_*). The mp3
// fixture carries embedded attached_pic cover art — the real-world mp3 shape
// that used to misclassify as Video (probe::detect_kind regression): if that
// regresses, the placed layer is a VideoClip whose proxy can never land and
// the export-ready wait times out loudly.
const FORMATS = ["wav", "mp3", "flac", "m4a", "ogg"];

describe("audio-only format matrix (real WebView2)", function () {
  before(function () {
    mkdirSync(PROJECT_PARENT_FORMATS, { recursive: true });
  });

  for (const fmt of FORMATS) {
    const source = fixture(`test_tones_10s.${fmt}`);
    const output = tmpOut(`weftcut-e2e-audiofmt-${fmt}.m4a`);

    it(`${fmt} source -> audio export stays aligned + faithful`, async function () {
      if (!existsSync(source)) {
        console.warn(`[e2e] SKIP: audio source not found at ${source}`);
        this.skip();
      }
      rmSync(output, { force: true });

      await newProject({
        parentFolder: PROJECT_PARENT_FORMATS,
        name: `e2e-audiofmt-${fmt}-` + Date.now(),
        canvas: { width: 1920, height: 1080, fpsNum: 30, fpsDen: 1 },
      });

      const r = await driveExport(
        {
          mediaAbsPath: source,
          outputAbsPath: output,
          settings: { includeVideo: false, includeAudio: true },
        },
        { timeout: 150000 },
      );
      if (!r.done.ok) {
        throw new Error(
          `exportClip failed: ${r.done.error} | exportState kind=${r.lastKind} detail=${r.lastDetail}`,
        );
      }

      const report = analyze({ output, source, samples: [0], audio: true });
      console.log(`[e2e] audio-only report ${fmt}:`, JSON.stringify(report));

      const misaligned = report.samples.filter((s) => !s.aligned);
      if (misaligned.length > 0) {
        throw new Error("audio seconds misaligned: " +
          JSON.stringify(misaligned.map((s) => ({ second: s.second, detected: s.detected_freq }))));
      }
      expect(Math.abs(report.drift_slope - 1)).toBeLessThanOrEqual(0.01);
      expect(Math.abs(report.offset_ms)).toBeLessThanOrEqual(66);
      expect(report.pass).toBe(true);
    });
  }
});

// ─── 3. Audio envelope conformance ───────────────────────────────────────────
// Audio-engine conformance (docs/audio.md §Testing): the deterministic Rust
// mixer upgrades audio assertions from perceptual (Goertzel tones) to
// ANALYTIC — windowed-RMS envelopes against closed-form expectations, the
// alimiter ceiling, and the equal-power pan law's L/R energy ratio.
//
// Keyframed-gain note: there is no keyframe IPC/hook surface to drive yet,
// so the keyframed-gain case is locked at the math level instead (the
// cross-language envelope goldens + `audio::mix` unit tests); the fade
// scenarios here exercise the same sampled-envelope pipeline end-to-end.

/// Boot a fresh 30fps project and run exportClip with audio patches.
async function bootAndExport({ output, audioPatches, settings }) {
  await newProject({
    parentFolder: PROJECT_PARENT_ENVELOPE,
    name: "e2e-audio-env-" + Date.now(),
    canvas: { width: 1920, height: 1080, fpsNum: 30, fpsDen: 1 },
  });

  const args = { mediaAbsPath: SOURCE, outputAbsPath: output };
  if (audioPatches) args.audioPatches = audioPatches;
  if (settings) args.settings = settings;

  const r = await driveExport(args);
  if (!r.done.ok) {
    throw new Error(
      `exportClip failed: ${r.done.error} | exportState kind=${r.lastKind} detail=${r.lastDetail}`,
    );
  }
}

describe("audio envelope conformance (real WebView2)", function () {
  before(function () {
    if (!existsSync(SOURCE)) {
      console.warn(`[e2e] SKIP suite: source not found at ${SOURCE}`);
      this.skip();
    }
    mkdirSync(PROJECT_PARENT_ENVELOPE, { recursive: true });
  });

  it("fade-in shapes the exported RMS envelope analytically", async function () {
    // 1 s linear fade-in at unity gain: window RMS deltas vs the loudest
    // window are 20·log10(t) — −12.04 dB at 0.25 s, −6.02 at 0.5 s,
    // −2.50 at 0.75 s, 0 in the body. ±1.5 dB bound absorbs AAC + the
    // −1 dB limiter ceiling on a hot fixture.
    const output = tmpOut("weftcut-e2e-fadein.mp4");
    rmSync(output, { force: true });

    await bootAndExport({
      output,
      audioPatches: [{ fade_in_us: 1_000_000 }],
    });

    const report = analyzeAudioEnvelope({
      output,
      expects: [
        { t_s: 0.25, expect_rms_db_delta: -12.04 },
        { t_s: 0.5, expect_rms_db_delta: -6.02 },
        { t_s: 0.75, expect_rms_db_delta: -2.5 },
        { t_s: 5.0, expect_rms_db_delta: 0.0 },
      ],
    });
    console.log("[e2e] fade-in envelope report:", JSON.stringify(report));
    expect(report.pass).toBe(true);
  });

  it("fade-out shapes the tail and static gain offsets the body", async function () {
    // −6 dB static gain + 1 s fade-out on a 10 s clip: the loudest window
    // is the body (the gain is uniform, so deltas are gain-independent);
    // the tail ramps down −6.02 dB at 9.5 s, −12.04 dB at 9.75 s.
    const output = tmpOut("weftcut-e2e-fadeout.mp4");
    rmSync(output, { force: true });

    await bootAndExport({
      output,
      audioPatches: [{ gain_db: -6, fade_out_us: 1_000_000 }],
    });

    const report = analyzeAudioEnvelope({
      output,
      expects: [
        { t_s: 5.0, expect_rms_db_delta: 0.0 },
        { t_s: 9.5, expect_rms_db_delta: -6.02 },
        { t_s: 9.75, expect_rms_db_delta: -12.04 },
      ],
    });
    console.log("[e2e] fade-out envelope report:", JSON.stringify(report));
    expect(report.pass).toBe(true);
  });

  it("two overlapping layers sum and the limiter holds the -1 dB ceiling", async function () {
    // The same clip stacked twice (0 dB + −6 dB). Whatever the fixture's
    // own level, the summed peak must never exceed the alimiter ceiling
    // (−1 dB ≈ −0.9 dBFS with codec slop).
    const output = tmpOut("weftcut-e2e-overlap.mp4");
    rmSync(output, { force: true });

    await bootAndExport({
      output,
      audioPatches: [{}, { gain_db: -6 }],
    });

    const report = analyzeAudioEnvelope({
      output,
      expects: [{ t_s: 5.0, expect_rms_db_delta: 0.0 }],
      peakMaxDb: -0.9,
    });
    console.log("[e2e] overlap+limiter report:", JSON.stringify(report));
    expect(report.peak_ceiling_pass).toBe(true);
    expect(report.pass).toBe(true);
  });

  it("pan -0.8 lands the equal-power L/R energy ratio", async function () {
    // Equal-power law with correlated channels collapses to
    // cot(x·π/2 / 2)… concretely for pan = −0.8: L−R = 20·log10(cot(0.05π))
    // ≈ +16.0 dB. (Mono and stereo inputs agree for identical-channel
    // content — the cross-bleed term makes the stereo law collapse to the
    // mono law's ratio.)
    const output = tmpOut("weftcut-e2e-pan.mp4");
    rmSync(output, { force: true });

    await bootAndExport({
      output,
      audioPatches: [{ pan: -0.8 }],
    });

    const report = analyzeAudioPan({ output, expectLrDb: 16.0 });
    console.log("[e2e] pan report:", JSON.stringify(report));
    expect(report.pass).toBe(true);
  });
});

// ─── 4. Role-based mixing conformance ────────────────────────────────────────
// Proves the audio-roles feature end-to-end: audio now mixes by per-layer ROLE
// (Dialogue/Music/SFX/Voiceover), and ROLE mute/solo + role gain gate the mix —
// track mute/solo no longer do (docs/audio.md §Roles, ADR 0023).
//
// The fixture is the single-tone-per-second source (one tone present at a time),
// so two copies of it carry identical, correlated content — they can't be told
// apart by frequency. We separate them in the STEREO FIELD instead and read the
// per-channel RMS ratio with the existing `--audio-pan` analyzer: tag one copy
// `dialogue` panned left and the other `music` panned right, and the channel a
// role lands in becomes its observable "band".
//
// With the equal-power mono pan law (StereoPannerNode), a layer at pan x has
// gainL = cos((x+1)·π/4), gainR = sin((x+1)·π/4). At x = ∓0.6 neither channel is
// ever truly silent (no -inf / JSON null), so the ratio stays finite and exactly
// computable whichever roles are audible:
//   • both roles audible → L and R each carry one full layer of the SAME signal
//     ⇒ L−R = 0 dB (symmetric);
//   • music role muted → only the left-panned dialogue survives
//     ⇒ L−R = 20·log10(cos18°/sin18°) = +9.77 dB.
// The +9.77 dB flip is the proof the music layer's contribution is GONE while
// dialogue remains — asserted on the analyzer's native ±1 dB pan tolerance, no
// loosening. A Goertzel `--audio` pass on the same muted-music output confirms
// dialogue's per-second tone content itself survived (not just the channel).
//
// Role flags/gain are driven by the real IPC the Mixer panel uses
// (`update_role_flags` / `set_role_gain`); the per-layer role + pan are set with
// `update_layer_params` (the `role` field on AudioPatch). Setup is composed
// manually (import + place same source twice, then export the timeline) rather
// than via the `exportClip` hook, because the role-flag mutation has to land
// BETWEEN patching the layers and running the export.

const ROLE_PAN = 0.6;
// L−R for the lone left-panned (−0.6) dialogue layer after music is silenced.
const DIALOGUE_ONLY_LR_DB =
  20 *
  Math.log10(
    Math.cos(((-ROLE_PAN + 1) * Math.PI) / 4) / Math.sin(((-ROLE_PAN + 1) * Math.PI) / 4),
  );

/// The auto-paired Audio layer ids, in placement order, from the live project
/// summary. Throws if fewer than `min` exist (auto-pair off, or the fixture
/// lacks an audio stream) — the same guard the exportClip hook uses.
async function audioLayerIds(min = 1) {
  const sum = await summary();
  const ids = [];
  for (const tr of sum.tracks) {
    for (const l of tr.layers) {
      if (l.params.kind === "Audio") ids.push(l.id);
    }
  }
  if (ids.length < min) {
    throw new Error(
      `expected ≥${min} auto-paired Audio layer(s), found ${ids.length} — is auto_pair_audio_on_import off, or does the fixture lack an audio stream?`,
    );
  }
  return ids;
}

describe("audio role mixing conformance (real WebView2)", function () {
  before(function () {
    if (!existsSync(SOURCE)) {
      console.warn(`[e2e] SKIP suite: source not found at ${SOURCE}`);
      this.skip();
    }
    mkdirSync(PROJECT_PARENT_ROLES, { recursive: true });
  });

  it("muting the music role drops the music layer while dialogue remains", async function () {
    const output = tmpOut("weftcut-e2e-role-mute.mp4");
    rmSync(output, { force: true });

    await newProject({
      parentFolder: PROJECT_PARENT_ROLES,
      name: "e2e-audio-roles-" + Date.now(),
      canvas: { width: 1920, height: 1080, fpsNum: 30, fpsDen: 1 },
    });
    await waitForHook("exportTimeline");

    // Import once, place the SAME media twice (one mediaId, two layers) so the
    // two audio copies are byte-identical content separated only by role + pan.
    const first = await browser.executeAsync((p, done) => {
      window.__weftcutTest
        .importAndPlaceMedia({ mediaAbsPath: p, tStartUs: 0 })
        .then((x) => done({ ok: true, ...x }))
        .catch((e) => done({ ok: false, error: String(e) }));
    }, SOURCE);
    if (!first.ok) throw new Error(`importAndPlaceMedia failed: ${first.error}`);
    const mediaId = first.mediaId;

    const second = await browser.executeAsync((id, done) => {
      window.__weftcutTest
        .placeMediaLayer({ mediaId: id, tStartUs: 0 })
        .then((x) => done({ ok: true, ...x }))
        .catch((e) => done({ ok: false, error: String(e) }));
    }, mediaId);
    if (!second.ok) throw new Error(`placeMediaLayer failed: ${second.error}`);

    // Tag the two auto-paired Audio layers: dialogue hard-ish left, music
    // hard-ish right (∓0.6 keeps both channels finite under either mix).
    const [dialogueLayer, musicLayer] = await audioLayerIds(2);
    await invokeCmd("update_layer_params", {
      layerId: dialogueLayer,
      patch: { kind: "Audio", role: "dialogue", pan: -ROLE_PAN },
    });
    await invokeCmd("update_layer_params", {
      layerId: musicLayer,
      patch: { kind: "Audio", role: "music", pan: ROLE_PAN },
    });

    // Sanity: both roles audible ⇒ symmetric stereo field (L−R ≈ 0 dB). This
    // is the baseline the mute then has to break.
    const baselineOut = tmpOut("weftcut-e2e-role-baseline.mp4");
    rmSync(baselineOut, { force: true });
    let r = await driveExport({ outputAbsPath: baselineOut }, { hook: "exportTimeline" });
    if (!r.done.ok) throw new Error(`baseline export failed: ${r.done.error}`);
    const baseline = analyzeAudioPan({ output: baselineOut, expectLrDb: 0.0 });
    console.log("[e2e] role baseline pan report:", JSON.stringify(baseline));
    expect(baseline.pass).toBe(true);

    // Mute the MUSIC role (the right-panned layer). Track mute/solo no longer
    // gate audio — this role flag is the only lever that silences the music.
    await invokeCmd("update_role_flags", { role: "music", patch: { muted: true } });

    r = await driveExport({ outputAbsPath: output }, { hook: "exportTimeline" });
    if (!r.done.ok) {
      throw new Error(
        `role-mute export failed: ${r.done.error} | exportState kind=${r.lastKind} detail=${r.lastDetail}`,
      );
    }

    // The right channel collapses to dialogue's small right-bleed: L−R jumps to
    // the lone-left-panned-dialogue value (+9.77 dB), proving the music layer's
    // contribution is gone. Native ±1 dB pan tolerance; no loosening.
    const muted = analyzeAudioPan({ output, expectLrDb: DIALOGUE_ONLY_LR_DB });
    console.log(
      `[e2e] role-mute pan report (expect L−R≈${DIALOGUE_ONLY_LR_DB.toFixed(2)} dB):`,
      JSON.stringify(muted),
    );
    expect(muted.pass).toBe(true);
    // And it really moved off the symmetric baseline (defensive: a no-op mute
    // would leave L−R ≈ 0).
    expect(muted.lr_delta_db).toBeGreaterThan(baseline.lr_delta_db + 3);

    // Dialogue's own per-second tone content survived the mix (the mono
    // downmix still tracks the 400+120k Hz markers + stays aligned).
    const tones = analyze({ output, source: SOURCE, samples: [0], audio: true });
    console.log("[e2e] role-mute tone report:", JSON.stringify(tones));
    expect(tones.samples.filter((s) => !s.aligned)).toHaveLength(0);
    expect(tones.pass).toBe(true);
  });

  it("role gain trims the role's level by the analytic dB factor", async function () {
    // A single dialogue layer (centered), exported at role gain 0 dB then at
    // −12 dB. Role gain folds uniformly into the layer's gain envelope, so the
    // file's absolute sample peak scales by the same factor: −12 dB ⇒ ×0.251.
    // We read `peak_dbfs` from the envelope analyzer (absolute dBFS) across the
    // two exports and assert the drop. Going DOWN keeps the −1 dB alimiter out
    // of the picture, so the peak ratio is the clean gain ratio. ±1.5 dB is the
    // envelope suite's own AAC bound — not loosened here.
    const ROLE_GAIN_DB = -12;
    const out0 = tmpOut("weftcut-e2e-role-gain-0.mp4");
    const outDown = tmpOut("weftcut-e2e-role-gain-down.mp4");

    // A trivial always-true expectation just to get a populated report; we only
    // read `peak_dbfs` (the loudest window vs itself is 0 dB by construction).
    const expects = [{ t_s: 5.0, expect_rms_db_delta: 0.0 }];

    /// Boot a fresh single-dialogue-layer project, set the dialogue role gain,
    /// export, and return the file's absolute peak dBFS.
    const exportAtRoleGain = async (output, gainDb) => {
      rmSync(output, { force: true });
      await newProject({
        parentFolder: PROJECT_PARENT_ROLES,
        name: "e2e-audio-rolegain-" + Date.now(),
        canvas: { width: 1920, height: 1080, fpsNum: 30, fpsDen: 1 },
      });
      await waitForHook("exportTimeline");

      const placed = await browser.executeAsync((p, done) => {
        window.__weftcutTest
          .importAndPlaceMedia({ mediaAbsPath: p, tStartUs: 0 })
          .then((x) => done({ ok: true, ...x }))
          .catch((e) => done({ ok: false, error: String(e) }));
      }, SOURCE);
      if (!placed.ok) throw new Error(`importAndPlaceMedia failed: ${placed.error}`);

      const [layer] = await audioLayerIds();
      await invokeCmd("update_layer_params", {
        layerId: layer,
        patch: { kind: "Audio", role: "dialogue", pan: 0 },
      });
      await invokeCmd("set_role_gain", { role: "dialogue", gainDb });

      const r = await driveExport({ outputAbsPath: output }, { hook: "exportTimeline" });
      if (!r.done.ok) {
        throw new Error(
          `role-gain export failed (gain ${gainDb} dB): ${r.done.error} | kind=${r.lastKind} detail=${r.lastDetail}`,
        );
      }
      const report = analyzeAudioEnvelope({ output, expects });
      console.log(`[e2e] role-gain ${gainDb} dB envelope report:`, JSON.stringify(report));
      return report.peak_dbfs;
    };

    const peakUnity = await exportAtRoleGain(out0, 0);
    const peakDown = await exportAtRoleGain(outDown, ROLE_GAIN_DB);

    // The peak fell by ~|ROLE_GAIN_DB|, proving role gain reached the export
    // mixer and folded into the layer's level.
    const drop = peakUnity - peakDown;
    console.log(
      `[e2e] role-gain peak drop: ${drop.toFixed(2)} dB (expect ≈ ${-ROLE_GAIN_DB} dB)`,
    );
    expect(Math.abs(drop - -ROLE_GAIN_DB)).toBeLessThanOrEqual(1.5);
  });
});
