// ONE-OFF PROBES (NOT gates) — float16 working-space exploration, P1–P5.
// Spec: docs/superpowers/specs/2026-06-12-float16-pipeline-exploration.md
//
//   P1  VideoFrame.copyTo() of 10-bit frames — can 10-bit pixels reach our
//       memory at all? (HEVC Main10 fixture = likely HW decode; an extra
//       H.264 Hi10P variant = known SW decode path.)
//   P2  Pixi 8.18 rgba16float RenderTexture — can the composite be RGBA16F
//       without forking Pixi? Custom WGSL gradient mesh + raw GPUTexture
//       readback, count distinct float16 steps (>256 = pass).
//   P3  GPU readback + Tauri IPC throughput — is the export exit fast
//       enough? Targets: 1080p30 P010 realtime ≈ 190 MB/s; ≥ 60 MB/s
//       acceptable for offline (0.3× realtime).
//   P4  float16 2D canvas drawImage precision — does the minimal-change
//       snapshot route preserve >8-bit?
//   P5  HDR glass — programmatic half only (matchMedia + canvas configure
//       echo). Visual presentation needs HDR-mode Windows + HDR display.
//
// Self-contained: mediabunny + pixi.js are injected from node_modules as
// blob-URL ES modules (csp is null; withGlobalTauri exposes convertFileSrc
// and the fs/path plugin APIs). Every test passes unconditionally except on
// harness-level failure — we're probing, not gating; verdicts go to stdout.
//
// Run (from apps/desktop/e2e — npx/npm silently drop --spec on Windows):
//   node node_modules\@wdio\cli\bin\wdio.js run wdio.conf.mjs --spec ./tools/float16_probes.e2e.js
//
// The H.264 Hi10P fixture is generated by fixtures/generate.go --gradient-h264:
//   ffmpeg -y -f lavfi -i "nullsrc=size=1920x1080:rate=30:duration=1" \
//     -vf "format=yuv420p10le,geq=lum='(X/(W-1))*1023':cb=512:cr=512,scale=out_color_matrix=bt709:out_range=tv" \
//     -c:v libx264 -profile:v high10 -pix_fmt yuv420p10le \
//     -colorspace bt709 -color_primaries bt709 -color_trc bt709 -color_range tv \
//     -an fixtures/media/test_1080p_gradient10_h264.mp4

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(HERE, "..", "..", "..", ".."); // e2e/tools -> repo root
const MEDIA = process.env.WEFTCUT_TEST_MEDIA || path.resolve(HERE, "..", "fixtures", "media");
const GRADIENT_HEVC = path.join(MEDIA, "test_1080p_gradient10.mp4");
const GRADIENT_H264 = path.join(MEDIA, "test_1080p_gradient10_h264.mp4");
const MEDIABUNNY_SRC = fs.readFileSync(
  path.resolve(REPO, "node_modules/mediabunny/dist/bundles/mediabunny.min.mjs"),
  "utf8",
);
const PIXI_SRC = fs.readFileSync(
  path.resolve(REPO, "node_modules/pixi.js/dist/pixi.min.mjs"),
  "utf8",
);

/// Ship a library source into the page in chunks (single executeScript
/// payloads in the MB range can exceed driver body limits).
async function stashLibSource(name, src) {
  await browser.execute((n) => {
    window.__probeSrc = window.__probeSrc || {};
    window.__probeSrc[n] = "";
  }, name);
  const CHUNK = 256 * 1024;
  for (let i = 0; i < src.length; i += CHUNK) {
    await browser.execute(
      (n, c) => {
        window.__probeSrc[n] += c;
      },
      name,
      src.slice(i, i + CHUNK),
    );
  }
}

describe("float16 pipeline probes (P1–P5, real WebView2)", function () {
  before(async function () {
    this.timeout(300000);
    await browser.setTimeout({ script: 240000 });
    await stashLibSource("mediabunny", MEDIABUNNY_SRC);
    await stashLibSource("pixi", PIXI_SRC);
    await browser.execute(() => {
      window.__probeMods = {};
      window.__probeImport = async (name) => {
        if (window.__probeMods[name]) return window.__probeMods[name];
        const blob = new Blob([window.__probeSrc[name]], { type: "text/javascript" });
        const url = URL.createObjectURL(blob);
        try {
          const m = await import(url);
          window.__probeMods[name] = m;
          return m;
        } finally {
          URL.revokeObjectURL(url);
        }
      };
      // Decode the first packet of `absPath` and return the output frames.
      // Lone keyframe from a possibly-B-frame stream ⇒ flush() is REQUIRED
      // or the decoder parks the frame and reads as "no output" (see
      // reference_lone_idr_needs_flush).
      window.__probeDecodeFirst = async (absPath, hwPref) => {
        const mb = await window.__probeImport("mediabunny");
        const url = window.__TAURI__.core.convertFileSrc(absPath);
        const resp = await fetch(url);
        if (!resp.ok) throw new Error(`fetch ${resp.status} for ${url}`);
        const buf = await resp.arrayBuffer();
        const input = new mb.Input({
          formats: mb.ALL_FORMATS,
          source: new mb.BufferSource(buf),
        });
        const track = await input.getPrimaryVideoTrack();
        if (!track) throw new Error("no video track");
        const config = await track.getDecoderConfig();
        const frames = [];
        const errors = [];
        const dec = new VideoDecoder({
          output: (f) => frames.push(f),
          error: (e) => errors.push(String(e)),
        });
        dec.configure({ ...config, ...(hwPref ? { hardwareAcceleration: hwPref } : {}) });
        const sink = new mb.EncodedPacketSink(track);
        const first = await sink.getFirstPacket();
        if (!first) throw new Error("no packets");
        dec.decode(first.toEncodedVideoChunk());
        try {
          await dec.flush();
        } catch (e) {
          errors.push("flush: " + String(e));
        }
        try {
          dec.close();
        } catch {
          /* already closed on error */
        }
        return { frames, errors, codec: config.codec };
      };
    });
  });

  it("P1 — VideoFrame.copyTo() of 10-bit frames", async function () {
    this.timeout(120000);
    const cases = [
      { label: "hevc-main10 / default", file: GRADIENT_HEVC, hw: null },
      { label: "hevc-main10 / prefer-software", file: GRADIENT_HEVC, hw: "prefer-software" },
      { label: "h264-hi10p / default", file: GRADIENT_H264, hw: null },
    ];
    const results = [];
    for (const c of cases) {
      if (!fs.existsSync(c.file)) {
        results.push({ label: c.label, skipped: "fixture missing: " + c.file });
        continue;
      }
      // eslint-disable-next-line no-await-in-loop
      const r = await browser.executeAsync(
        (absPath, hw, done) => {
          (async () => {
            const { frames, errors, codec } = await window.__probeDecodeFirst(absPath, hw);
            if (!frames.length) return done({ codec, errors, noFrame: true });
            const f = frames[0];
            const out = {
              codec,
              errors,
              format: f.format,
              codedWidth: f.codedWidth,
              codedHeight: f.codedHeight,
              colorSpace: f.colorSpace
                ? {
                    primaries: f.colorSpace.primaries,
                    transfer: f.colorSpace.transfer,
                    matrix: f.colorSpace.matrix,
                    fullRange: f.colorSpace.fullRange,
                  }
                : null,
            };
            try {
              // Opaque HW frames (format=null) can't be sized natively; some
              // Chromium versions support copyTo format CONVERSION — probe
              // I420P10 explicitly before giving up on the frame.
              let convertedTo = null;
              let copyOpts;
              if (f.format == null) {
                try {
                  f.allocationSize({ format: "I420P10" });
                  copyOpts = { format: "I420P10" };
                  convertedTo = "I420P10";
                } catch (e) {
                  out.convertProbe = "allocationSize({format:'I420P10'}) threw: " + String(e);
                }
              }
              out.convertedTo = convertedTo;
              const size = f.allocationSize(copyOpts);
              const buf = new ArrayBuffer(size);
              const layout = await f.copyTo(buf, copyOpts);
              out.allocationSize = size;
              out.layout = layout.map((p) => ({ offset: p.offset, stride: p.stride }));
              const fmt = String(convertedTo ?? f.format ?? "");
              const is10 = /P1[02]A?$/.test(fmt); // I420P10 / I420P12 / I420AP10 ...
              out.parsedAs10bit = is10;
              const midRow = (View, bytesPer) => {
                const p0 = layout[0];
                const off = p0.offset + p0.stride * (f.codedHeight >> 1);
                const row = new View(buf, off, f.codedWidth);
                let mx = 0;
                const distinct = new Set();
                for (let x = 0; x < f.codedWidth; x++) {
                  const v = row[x];
                  if (v > mx) mx = v;
                  distinct.add(v);
                }
                return {
                  bytesPerSample: bytesPer,
                  max: mx,
                  distinct: distinct.size,
                  first: row[0],
                  last: row[f.codedWidth - 1],
                };
              };
              out.midRow = is10 ? midRow(Uint16Array, 2) : midRow(Uint8Array, 1);
            } catch (e) {
              out.copyToError = String(e);
            }
            frames.forEach((fr) => fr.close());
            done(out);
          })().catch((e) => done({ fatal: String((e && e.stack) || e) }));
        },
        c.file,
        c.hw,
      );
      results.push({ label: c.label, ...r });
    }

    console.log("\n[P1] ===== VideoFrame.copyTo() of 10-bit frames =====");
    for (const r of results) {
      console.log(`[P1] --- ${r.label} ---`);
      if (r.skipped) {
        console.log("[P1]   SKIPPED:", r.skipped);
        continue;
      }
      if (r.fatal) {
        console.log("[P1]   FATAL:", r.fatal);
        continue;
      }
      console.log(
        `[P1]   codec=${r.codec} format=${r.format} ${r.codedWidth}x${r.codedHeight} colorSpace=${JSON.stringify(r.colorSpace)}`,
      );
      if (r.errors?.length) console.log("[P1]   decoderErrors:", r.errors);
      if (r.noFrame) {
        console.log("[P1]   NO FRAME OUTPUT");
        continue;
      }
      if (r.copyToError) console.log("[P1]   copyTo ERROR:", r.copyToError);
      if (r.convertProbe) console.log("[P1]   convert probe:", r.convertProbe);
      if (r.convertedTo) console.log("[P1]   copyTo format-converted to:", r.convertedTo);
      if (r.layout) console.log("[P1]   allocationSize:", r.allocationSize, "layout:", JSON.stringify(r.layout));
      if (r.midRow) {
        const verdict =
          r.parsedAs10bit && r.midRow.max > 255 && r.midRow.distinct > 256
            ? "✅ >8-bit pixels reached our memory"
            : "❌ no >8-bit data (8-bit format or collapsed ramp)";
        console.log(
          `[P1]   midRow: max=${r.midRow.max} distinct=${r.midRow.distinct} first=${r.midRow.first} last=${r.midRow.last} -> ${verdict}`,
        );
      }
    }
    expect(results.some((r) => !r.fatal && !r.skipped)).toBe(true);
  });

  it("P2 — Pixi 8.18 rgba16float render target", async function () {
    this.timeout(120000);
    const r = await browser.executeAsync((done) => {
      (async () => {
        const PIXI = await window.__probeImport("pixi");
        const out = { pixiVersion: PIXI.VERSION };
        const renderer = await PIXI.autoDetectRenderer({
          preference: "webgpu",
          width: 64,
          height: 64,
          antialias: false,
        });
        out.rendererName = renderer.name ?? renderer.constructor.name;
        if (!renderer.gpu) {
          done({ ...out, error: "WebGPU renderer not active (fell back to WebGL?)" });
          return;
        }
        const device = renderer.gpu.device;
        const gpuErrors = [];
        device.addEventListener?.("uncapturederror", (e) =>
          gpuErrors.push(String(e.error?.message ?? e)),
        );

        const W = 4096;
        const H = 16;
        const rt = PIXI.RenderTexture.create({ width: W, height: H, format: "rgba16float" });
        out.rtSourceFormat = rt.source.format;

        // Gradient must be generated IN THE FRAGMENT SHADER: every Pixi
        // built-in color path (batcher vertex colors, FillGradient textures)
        // quantizes to 8-bit and would fake a failure.
        const wgsl = `
          struct GlobalUniforms {
            uProjectionMatrix:mat3x3<f32>,
            uWorldTransformMatrix:mat3x3<f32>,
            uWorldColorAlpha: vec4<f32>,
            uResolution: vec2<f32>,
          }
          @group(0) @binding(0) var<uniform> globalUniforms : GlobalUniforms;
          struct VSOut {
            @builtin(position) position: vec4<f32>,
            @location(0) vUV: vec2<f32>,
          }
          @vertex
          fn vmain(@location(0) aPosition: vec2<f32>, @location(1) aUV: vec2<f32>) -> VSOut {
            var out: VSOut;
            let clip = globalUniforms.uProjectionMatrix * globalUniforms.uWorldTransformMatrix * vec3<f32>(aPosition, 1.0);
            out.position = vec4<f32>(clip.xy, 0.0, 1.0);
            out.vUV = aUV;
            return out;
          }
          @fragment
          fn fmain(@location(0) vUV: vec2<f32>) -> @location(0) vec4<f32> {
            return vec4<f32>(vUV.x, vUV.x, vUV.x, 1.0);
          }
        `;
        const geometry = new PIXI.MeshGeometry({
          positions: new Float32Array([0, 0, W, 0, W, H, 0, H]),
          uvs: new Float32Array([0, 0, 1, 0, 1, 1, 0, 1]),
          indices: new Uint32Array([0, 1, 2, 0, 2, 3]),
        });
        const shader = PIXI.Shader.from({
          gpu: {
            vertex: { entryPoint: "vmain", source: wgsl },
            fragment: { entryPoint: "fmain", source: wgsl },
          },
          resources: {},
        });
        const mesh = new PIXI.Mesh({ geometry, shader });
        try {
          renderer.render({ container: mesh, target: rt });
          out.customShaderRender = "ok";
        } catch (e) {
          out.customShaderRender = "threw: " + String(e);
        }
        // uncapturederror delivery is async — settle before bucketing, or
        // stock-render errors masquerade as patched-render errors (run-2 bug).
        await device.queue.onSubmittedWorkDone();
        await new Promise((r2) => setTimeout(r2, 100));
        out.stockGpuErrors = gpuErrors.splice(0);

        // Pixi 8.18.1 hardcodes the pipeline colorTarget format to
        // "bgra8unorm" (GpuStateSystem.getColorTargets) and the pipeline
        // cache key ignores the target format — the render pass correctly
        // targets RGBA16Float but the pipeline doesn't, so the stock draw
        // validation-fails. Probe the SURGICAL override: derive the format
        // from the override knob, drop the stale pipeline cache, re-render.
        // If this works, "no fork" ≈ a ~20-line upstream fix / runtime patch,
        // NOT a bespoke composite pass.
        try {
          const state = renderer.state;
          const origGetColorTargets = state.getColorTargets.bind(state);
          state.getColorTargets = (st, count) => {
            const targets = origGetColorTargets(st, count);
            for (const t of targets) t.format = window.__probePixiTargetFormat ?? t.format;
            return targets;
          };
          window.__probePixiTargetFormat = "rgba16float";
          // render() re-enters setRenderTarget → _updatePipeHash, which
          // re-points _pipeCache at the cached _pipeStateCaches entry — the
          // stale bgra8unorm pipeline survives a bare _pipeCache reset. Both
          // levels must go.
          renderer.pipeline._pipeStateCaches = Object.create(null);
          renderer.pipeline._pipeCache = Object.create(null);
          renderer.render({ container: mesh, target: rt });
          await device.queue.onSubmittedWorkDone();
          out.patchedRender = "ok";
          window.__probePixiTargetFormat = null;
        } catch (e) {
          out.patchedRender = "threw: " + String(e);
        }
        await new Promise((r2) => setTimeout(r2, 100));
        out.patchedGpuErrors = gpuErrors.splice(0);

        try {
          const tex = renderer.texture.getGpuSource(rt.source);
          out.gpuTextureFormat = tex.format;
          const bytesPerRow = W * 8; // rgba16float, 4096*8 is 256-aligned
          const rb = device.createBuffer({
            size: bytesPerRow * H,
            usage: GPUBufferUsage.COPY_DST | GPUBufferUsage.MAP_READ,
          });
          const enc = device.createCommandEncoder();
          enc.copyTextureToBuffer(
            { texture: tex },
            { buffer: rb, bytesPerRow, rowsPerImage: H },
            [W, H, 1],
          );
          device.queue.submit([enc.finish()]);
          await rb.mapAsync(GPUMapMode.READ);
          const u16 = new Uint16Array(rb.getMappedRange());
          const f16 = (h) => {
            const s = h & 0x8000 ? -1 : 1;
            const e = (h >> 10) & 0x1f;
            const m = h & 0x3ff;
            if (e === 0) return s * m * 2 ** -24;
            if (e === 31) return m ? NaN : s * Infinity;
            return s * (1 + m / 1024) * 2 ** (e - 15);
          };
          const rowBase = (H >> 1) * W * 4;
          const distinct = new Set();
          let monotonic = true;
          let prev = -Infinity;
          let minV = Infinity;
          let maxV = -Infinity;
          for (let x = 0; x < W; x++) {
            const bits = u16[rowBase + x * 4];
            const v = f16(bits);
            if (v < prev) monotonic = false;
            prev = v;
            if (v < minV) minV = v;
            if (v > maxV) maxV = v;
            distinct.add(bits);
          }
          rb.unmap();
          out.readback = { distinct: distinct.size, monotonic, min: minV, max: maxV };
        } catch (e) {
          out.readbackError = String(e);
        }
        // Let any pending uncapturederror events land before reporting.
        await new Promise((r2) => setTimeout(r2, 100));
        out.gpuErrors = gpuErrors.slice();
        try {
          renderer.destroy();
        } catch {
          /* ignore teardown */
        }
        done(out);
      })().catch((e) => done({ fatal: String((e && e.stack) || e) }));
    });

    console.log("\n[P2] ===== Pixi rgba16float render target =====");
    if (r.fatal) {
      console.log("[P2] FATAL:", r.fatal);
    } else {
      console.log(
        `[P2] pixi=${r.pixiVersion} renderer=${r.rendererName} rtFormat=${r.rtSourceFormat} gpuTexFormat=${r.gpuTextureFormat}`,
      );
      console.log(
        `[P2] stock render=${r.customShaderRender} gpuErrors=${r.stockGpuErrors?.length ?? 0}`,
      );
      if (r.stockGpuErrors?.length)
        console.log("[P2] stock validation error[0]:", r.stockGpuErrors[0].split("\n")[0]);
      console.log(
        `[P2] patched render (getColorTargets format override + pipe-cache reset)=${r.patchedRender} gpuErrors=${r.patchedGpuErrors?.length ?? 0}`,
      );
      if (r.patchedGpuErrors?.length)
        console.log("[P2] patched validation errors:", r.patchedGpuErrors);
      if (r.error) console.log("[P2] ERROR:", r.error);
      if (r.readbackError) console.log("[P2] readback ERROR:", r.readbackError);
      if (r.gpuErrors?.length) console.log("[P2] late GPU errors:", r.gpuErrors);
      if (r.readback) {
        const stockPass =
          r.readback.distinct > 256 && !r.stockGpuErrors?.length && r.customShaderRender === "ok";
        const patchedPass =
          r.readback.distinct > 256 &&
          r.patchedRender === "ok" &&
          !r.patchedGpuErrors?.length;
        console.log(
          `[P2] readback: distinct=${r.readback.distinct} monotonic=${r.readback.monotonic} min=${r.readback.min} max=${r.readback.max} -> ${
            stockPass
              ? "✅ float16 composite works through STOCK Pixi"
              : patchedPass
                ? "🟡 float16 composite works with a ~20-line getColorTargets format override (stock Pixi hardcodes bgra8unorm)"
                : "❌ does not demonstrate >8-bit (see fields above)"
          }`,
        );
      }
    }
    expect(r.fatal).toBeUndefined();
  });

  it("P2b — Pixi WebGL2 rgba16float render target (stock, no patch)", async function () {
    this.timeout(120000);
    const r = await browser.executeAsync((done) => {
      (async () => {
        const PIXI = await window.__probeImport("pixi");
        const out = { pixiVersion: PIXI.VERSION };
        const renderer = await PIXI.autoDetectRenderer({
          preference: "webgl",
          width: 64,
          height: 64,
          antialias: false,
        });
        out.rendererName = renderer.name ?? renderer.constructor.name;
        const gl = renderer.gl;
        if (!gl) {
          done({ ...out, error: "no GL context (WebGL renderer not active?)" });
          return;
        }
        out.glVersion = gl.getParameter(gl.VERSION);
        out.colorBufferFloat = !!gl.getExtension("EXT_color_buffer_float");

        const W = 4096;
        const H = 16;
        const rt = PIXI.RenderTexture.create({ width: W, height: H, format: "rgba16float" });
        out.rtSourceFormat = rt.source.format;

        // GLSL ES 3.0 twin of the P2 WGSL gradient mesh (Pixi GL mesh
        // conventions: plain uProjectionMatrix/uWorldTransformMatrix uniforms).
        const vert = `#version 300 es
          precision highp float;
          in vec2 aPosition;
          in vec2 aUV;
          out vec2 vUV;
          uniform mat3 uProjectionMatrix;
          uniform mat3 uWorldTransformMatrix;
          void main() {
            mat3 mvp = uProjectionMatrix * uWorldTransformMatrix;
            gl_Position = vec4((mvp * vec3(aPosition, 1.0)).xy, 0.0, 1.0);
            vUV = aUV;
          }`;
        const frag = `#version 300 es
          precision highp float;
          in vec2 vUV;
          out vec4 finalColor;
          void main() {
            finalColor = vec4(vUV.x, vUV.x, vUV.x, 1.0);
          }`;
        try {
          const geometry = new PIXI.MeshGeometry({
            positions: new Float32Array([0, 0, W, 0, W, H, 0, H]),
            uvs: new Float32Array([0, 0, 1, 0, 1, 1, 0, 1]),
            indices: new Uint32Array([0, 1, 2, 0, 2, 3]),
          });
          const shader = PIXI.Shader.from({
            gl: { vertex: vert, fragment: frag },
            resources: {},
          });
          const mesh = new PIXI.Mesh({ geometry, shader });
          renderer.render({ container: mesh, target: rt });
          out.render = "ok";
        } catch (e) {
          out.render = "threw: " + String(e);
        }

        try {
          // Re-bind the render texture's framebuffer and read the float row.
          renderer.renderTarget.bind(rt, false);
          const glErrBefore = gl.getError();
          const px = new Float32Array(W * 4);
          gl.readPixels(0, H >> 1, W, 1, gl.RGBA, gl.FLOAT, px);
          const glErr = gl.getError();
          out.glReadError = glErr || glErrBefore || 0;
          const distinct = new Set();
          let monotonic = true;
          let prev = -Infinity;
          let minV = Infinity;
          let maxV = -Infinity;
          for (let x = 0; x < W; x++) {
            const v = px[x * 4];
            if (v < prev) monotonic = false;
            prev = v;
            if (v < minV) minV = v;
            if (v > maxV) maxV = v;
            distinct.add(v);
          }
          out.readback = { distinct: distinct.size, monotonic, min: minV, max: maxV };
        } catch (e) {
          out.readbackError = String(e);
        }
        try {
          renderer.destroy();
        } catch {
          /* ignore teardown */
        }
        done(out);
      })().catch((e) => done({ fatal: String((e && e.stack) || e) }));
    });

    console.log("\n[P2b] ===== Pixi WebGL2 rgba16float render target (stock) =====");
    if (r.fatal) {
      console.log("[P2b] FATAL:", r.fatal);
    } else {
      console.log(
        `[P2b] pixi=${r.pixiVersion} renderer=${r.rendererName} gl=${r.glVersion} EXT_color_buffer_float=${r.colorBufferFloat} rtFormat=${r.rtSourceFormat}`,
      );
      console.log(`[P2b] render=${r.render} glReadError=${r.glReadError}`);
      if (r.error) console.log("[P2b] ERROR:", r.error);
      if (r.readbackError) console.log("[P2b] readback ERROR:", r.readbackError);
      if (r.readback) {
        const pass = r.readback.distinct > 256 && r.readback.monotonic && r.render === "ok";
        console.log(
          `[P2b] readback: distinct=${r.readback.distinct} monotonic=${r.readback.monotonic} min=${r.readback.min} max=${r.readback.max} -> ${
            pass
              ? "✅ STOCK Pixi WebGL2 renders into float16 with >8-bit precision (no patch needed)"
              : "❌ does not demonstrate >8-bit on WebGL2"
          }`,
        );
      }
    }
    expect(r.fatal).toBeUndefined();
  });

  it("P3 — GPU readback + Tauri IPC throughput", async function () {
    this.timeout(300000);
    const r = await browser.executeAsync((done) => {
      (async () => {
        const out = {};
        const MB = 1024 * 1024;
        const adapter = await navigator.gpu.requestAdapter();
        if (!adapter) return done({ fatal: "no WebGPU adapter" });
        const device = await adapter.requestDevice();
        out.adapter = adapter.info
          ? {
              vendor: adapter.info.vendor,
              architecture: adapter.info.architecture,
              description: adapter.info.description,
            }
          : null;

        // (a) GPU→CPU texture readback at full RGBA16F frame size (the
        // pre-pack upper bound; the designed pipeline packs to P010 on-GPU
        // first and reads back ~6 MB instead).
        async function benchTextureReadback(w, h, iters) {
          const bytesPerRow = Math.ceil((w * 8) / 256) * 256;
          const size = bytesPerRow * h;
          const tex = device.createTexture({
            size: [w, h],
            format: "rgba16float",
            usage: GPUTextureUsage.RENDER_ATTACHMENT | GPUTextureUsage.COPY_SRC,
          });
          {
            const enc = device.createCommandEncoder();
            const pass = enc.beginRenderPass({
              colorAttachments: [
                {
                  view: tex.createView(),
                  loadOp: "clear",
                  storeOp: "store",
                  clearValue: { r: 0.5, g: 0.25, b: 0.125, a: 1 },
                },
              ],
            });
            pass.end();
            device.queue.submit([enc.finish()]);
            await device.queue.onSubmittedWorkDone();
          }
          const buf = device.createBuffer({
            size,
            usage: GPUBufferUsage.COPY_DST | GPUBufferUsage.MAP_READ,
          });
          // warmup
          for (let i = 0; i < 3; i++) {
            const enc = device.createCommandEncoder();
            enc.copyTextureToBuffer(
              { texture: tex },
              { buffer: buf, bytesPerRow, rowsPerImage: h },
              [w, h, 1],
            );
            device.queue.submit([enc.finish()]);
            // eslint-disable-next-line no-await-in-loop
            await buf.mapAsync(GPUMapMode.READ);
            buf.unmap();
          }
          const t0 = performance.now();
          for (let i = 0; i < iters; i++) {
            const enc = device.createCommandEncoder();
            enc.copyTextureToBuffer(
              { texture: tex },
              { buffer: buf, bytesPerRow, rowsPerImage: h },
              [w, h, 1],
            );
            device.queue.submit([enc.finish()]);
            // eslint-disable-next-line no-await-in-loop
            await buf.mapAsync(GPUMapMode.READ);
            buf.unmap();
          }
          const ms = performance.now() - t0;
          tex.destroy();
          buf.destroy();
          return {
            frameMB: +(size / MB).toFixed(2),
            iters,
            ms: Math.round(ms),
            MBps: Math.round(((size * iters) / MB) / (ms / 1000)),
            fps: +(iters / (ms / 1000)).toFixed(1),
          };
        }
        out.texReadback1080 = await benchTextureReadback(1920, 1080, 30);
        out.texReadback4k = await benchTextureReadback(3840, 2160, 10);

        // (b) P010-sized buffer readback (what the post-pack exit reads).
        async function benchBufferReadback(sizeBytes, iters) {
          const src = device.createBuffer({
            size: sizeBytes,
            usage: GPUBufferUsage.COPY_SRC | GPUBufferUsage.COPY_DST,
          });
          const dst = device.createBuffer({
            size: sizeBytes,
            usage: GPUBufferUsage.COPY_DST | GPUBufferUsage.MAP_READ,
          });
          for (let i = 0; i < 3 + iters; i++) {
            if (i === 3) var t0 = performance.now(); // eslint-disable-line no-var
            const enc = device.createCommandEncoder();
            enc.copyBufferToBuffer(src, 0, dst, 0, sizeBytes);
            device.queue.submit([enc.finish()]);
            // eslint-disable-next-line no-await-in-loop
            await dst.mapAsync(GPUMapMode.READ);
            dst.unmap();
          }
          const ms = performance.now() - t0;
          src.destroy();
          dst.destroy();
          return {
            frameMB: +(sizeBytes / MB).toFixed(2),
            iters,
            ms: Math.round(ms),
            MBps: Math.round(((sizeBytes * iters) / MB) / (ms / 1000)),
            fps: +(iters / (ms / 1000)).toFixed(1),
          };
        }
        const P010_1080 = 1920 * 1080 * 3; // 1.5 planes × 2 B/sample
        const P010_4K = 3840 * 2160 * 3;
        out.bufReadback1080 = await benchBufferReadback(P010_1080, 30);
        out.bufReadback4k = await benchBufferReadback(P010_4K, 10);

        // (c) IPC: writeFile(append) of P010-sized chunks — the export's
        // production streaming pattern (raw-body invoke under the hood).
        const T = window.__TAURI__;
        if (!T?.fs?.writeFile || !T?.path?.tempDir) {
          out.ipcError = "window.__TAURI__.fs/path missing (withGlobalTauri plugin APIs absent)";
        } else {
          const tmpDir = await T.path.tempDir();
          async function benchIpc(label, chunkBytes, chunks) {
            const file = await T.path.join(
              tmpDir,
              `weftcut_f16probe_${label}_${Date.now().toString(36)}.bin`,
            );
            const payload = new Uint8Array(chunkBytes);
            for (let i = 0; i < payload.length; i += 4096) payload[i] = i & 0xff;
            await T.fs.writeFile(file, payload.subarray(0, 4096)); // create + warm path
            const t0 = performance.now();
            for (let i = 0; i < chunks; i++) {
              // eslint-disable-next-line no-await-in-loop
              await T.fs.writeFile(file, payload, { append: true });
            }
            const ms = performance.now() - t0;
            try {
              await T.fs.remove(file);
            } catch {
              /* leave temp garbage rather than fail the bench */
            }
            return {
              chunkMB: +(chunkBytes / MB).toFixed(2),
              chunks,
              ms: Math.round(ms),
              MBps: Math.round(((chunkBytes * chunks) / MB) / (ms / 1000)),
            };
          }
          out.ipc1080 = await benchIpc("1080", P010_1080, 20);
          out.ipc4k = await benchIpc("4k", P010_4K, 6);

          // (d) combined per-frame pipeline at 1080p P010: buffer readback →
          // copy out of mapped range → IPC write. The end-to-end exit rate.
          {
            const src = device.createBuffer({
              size: P010_1080,
              usage: GPUBufferUsage.COPY_SRC | GPUBufferUsage.COPY_DST,
            });
            const dst = device.createBuffer({
              size: P010_1080,
              usage: GPUBufferUsage.COPY_DST | GPUBufferUsage.MAP_READ,
            });
            const file = await T.path.join(
              tmpDir,
              `weftcut_f16probe_combined_${Date.now().toString(36)}.bin`,
            );
            await T.fs.writeFile(file, new Uint8Array(4096));
            const host = new Uint8Array(P010_1080);
            const frames = 15;
            const t0 = performance.now();
            for (let i = 0; i < frames; i++) {
              const enc = device.createCommandEncoder();
              enc.copyBufferToBuffer(src, 0, dst, 0, P010_1080);
              device.queue.submit([enc.finish()]);
              // eslint-disable-next-line no-await-in-loop
              await dst.mapAsync(GPUMapMode.READ);
              host.set(new Uint8Array(dst.getMappedRange()));
              dst.unmap();
              // eslint-disable-next-line no-await-in-loop
              await T.fs.writeFile(file, host, { append: true });
            }
            const ms = performance.now() - t0;
            try {
              await T.fs.remove(file);
            } catch {
              /* ignore */
            }
            src.destroy();
            dst.destroy();
            out.combined1080 = {
              frames,
              ms: Math.round(ms),
              MBps: Math.round(((P010_1080 * frames) / MB) / (ms / 1000)),
              fps: +(frames / (ms / 1000)).toFixed(1),
            };
          }
        }
        done(out);
      })().catch((e) => done({ fatal: String((e && e.stack) || e) }));
    });

    console.log("\n[P3] ===== GPU readback + IPC throughput =====");
    if (r.fatal) {
      console.log("[P3] FATAL:", r.fatal);
    } else {
      console.log("[P3] adapter:", JSON.stringify(r.adapter));
      const row = (label, b) =>
        b &&
        console.log(
          `[P3] ${label.padEnd(34)}: ${String(b.MBps).padStart(6)} MB/s  (${b.frameMB ?? b.chunkMB} MB × ${b.iters ?? b.chunks ?? b.frames}, ${b.ms} ms${b.fps ? `, ${b.fps} fps` : ""})`,
        );
      row("texture readback RGBA16F 1080p", r.texReadback1080);
      row("texture readback RGBA16F 4K", r.texReadback4k);
      row("buffer readback P010 1080p", r.bufReadback1080);
      row("buffer readback P010 4K", r.bufReadback4k);
      if (r.ipcError) console.log("[P3] IPC ERROR:", r.ipcError);
      row("IPC writeFile(append) P010 1080p", r.ipc1080);
      row("IPC writeFile(append) P010 4K", r.ipc4k);
      row("combined readback+IPC 1080p", r.combined1080);
      if (r.combined1080) {
        const v =
          r.combined1080.MBps >= 190
            ? "✅ ≥ realtime 1080p30 P010 (190 MB/s)"
            : r.combined1080.MBps >= 60
              ? "🟡 ≥ 0.3× realtime (60 MB/s) — acceptable for offline export"
              : "❌ below the 60 MB/s offline floor — batch frames / shared-memory transport before declaring dead";
        console.log(`[P3] verdict: ${v}`);
      }
    }
    expect(r.fatal).toBeUndefined();
  });

  it("P4 — float16 2D canvas drawImage precision", async function () {
    this.timeout(120000);
    const files = [
      { label: "hevc-main10", file: GRADIENT_HEVC },
      { label: "h264-hi10p", file: GRADIENT_H264 },
    ].filter((f) => fs.existsSync(f.file));
    const results = [];
    for (const c of files) {
      // eslint-disable-next-line no-await-in-loop
      const r = await browser.executeAsync((absPath, done) => {
        (async () => {
          const out = {};
          const { frames, errors } = await window.__probeDecodeFirst(absPath, null);
          if (!frames.length) return done({ error: "no frame decoded", errors });
          const f = frames[0];
          const W = f.codedWidth;
          const H = f.codedHeight;
          out.frameFormat = f.format;

          const rowStats = (data, w) => {
            const distinct = new Set();
            let monotonic = true;
            let prev = -Infinity;
            let minV = Infinity;
            let maxV = -Infinity;
            for (let x = 0; x < w; x++) {
              const v = data[x * 4];
              if (v < prev) monotonic = false;
              prev = v;
              if (v < minV) minV = v;
              if (v > maxV) maxV = v;
              distinct.add(v);
            }
            return { distinct: distinct.size, monotonic, min: minV, max: maxV };
          };

          try {
            const c2 = new OffscreenCanvas(W, H);
            const ctx = c2.getContext("2d", { colorType: "float16" });
            out.ctxAttrs = ctx.getContextAttributes ? ctx.getContextAttributes() : null;
            ctx.drawImage(f, 0, 0);
            // ImageDataSettings uses `pixelFormat` ("rgba-float16"), NOT the
            // context-attribute key `colorType` — unknown dict members are
            // silently ignored and you get unorm8 back (run-1 mistake).
            let id;
            try {
              id = ctx.getImageData(0, H >> 1, W, 1, { pixelFormat: "rgba-float16" });
            } catch (e) {
              out.getImageDataF16Error = String(e);
              id = ctx.getImageData(0, H >> 1, W, 1);
            }
            out.dataCtor = id.data.constructor.name;
            out.pixelFormat = id.pixelFormat ?? null;
            out.f16Row = rowStats(id.data, W);
          } catch (e) {
            out.f16Error = String(e);
          }

          // control: default 8-bit canvas of the same frame
          try {
            const c8 = new OffscreenCanvas(W, H);
            const ctx8 = c8.getContext("2d");
            ctx8.drawImage(f, 0, 0);
            const id8 = ctx8.getImageData(0, H >> 1, W, 1);
            out.u8Row = rowStats(id8.data, W);
          } catch (e) {
            out.u8Error = String(e);
          }

          frames.forEach((fr) => fr.close());
          done(out);
        })().catch((e) => done({ fatal: String((e && e.stack) || e) }));
      }, c.file);
      results.push({ label: c.label, ...r });
    }

    console.log("\n[P4] ===== float16 2D canvas drawImage precision =====");
    if (!results.length) console.log("[P4] SKIPPED: no 10-bit fixtures present");
    for (const r of results) {
      console.log(`[P4] --- ${r.label} ---`);
      if (r.fatal || r.error) {
        console.log("[P4]   ERROR:", r.fatal ?? r.error, r.errors ?? "");
        continue;
      }
      console.log(
        `[P4]   frameFormat=${r.frameFormat} ctxAttrs=${JSON.stringify(r.ctxAttrs)} data=${r.dataCtor} pixelFormat=${r.pixelFormat}`,
      );
      if (r.f16Error) console.log("[P4]   float16 canvas ERROR:", r.f16Error);
      if (r.getImageDataF16Error)
        console.log("[P4]   getImageData(float16) ERROR:", r.getImageDataF16Error);
      if (r.f16Row) {
        const pass = r.f16Row.distinct > 256;
        console.log(
          `[P4]   f16 row: distinct=${r.f16Row.distinct} monotonic=${r.f16Row.monotonic} min=${r.f16Row.min} max=${r.f16Row.max} -> ${
            pass
              ? "✅ drawImage preserved >8-bit"
              : "❌ quantized to ≤8-bit on the drawImage path"
          }`,
        );
      }
      if (r.u8Row)
        console.log(
          `[P4]   u8 control: distinct=${r.u8Row.distinct} min=${r.u8Row.min} max=${r.u8Row.max}`,
        );
    }
    expect(results.every((r) => !r.fatal)).toBe(true);
  });

  it("P5b — WebGL/2D-canvas HDR surface APIs (vs WebGPU's toneMapping)", async function () {
    this.timeout(60000);
    const r = await browser.executeAsync((done) => {
      (async () => {
        const out = {};

        // --- WebGL2: float16 backbuffer (drawingBufferStorage) + any
        // extended-range presentation control?
        const canvas = document.createElement("canvas");
        canvas.width = 64;
        canvas.height = 64;
        canvas.style.cssText = "position:fixed;left:-9999px;top:0";
        document.body.appendChild(canvas);
        // Try requesting toneMapping via context attributes (HDR-canvas
        // proposal shape) and see what echoes back.
        const gl = canvas.getContext("webgl2", { toneMapping: { mode: "extended" } });
        if (!gl) {
          out.webgl = { error: "no webgl2 context" };
        } else {
          const attrs = gl.getContextAttributes() ?? {};
          out.webgl = {
            ctxAttrsToneMapping: attrs.toneMapping ?? null,
            ctxAttrKeys: Object.keys(attrs),
            drawingBufferStorage: typeof gl.drawingBufferStorage === "function",
            // The Khronos-proposed presentation control (PR #3668) — the
            // WebGL twin of WebGPU's toneMapping. Method, not attribute.
            drawingBufferToneMapping: typeof gl.drawingBufferToneMapping,
            drawingBufferColorSpace:
              "drawingBufferColorSpace" in gl ? gl.drawingBufferColorSpace : null,
            drawingBufferFormatProp: "drawingBufferFormat" in gl ? gl.drawingBufferFormat : null,
            configureHighDynamicRange: typeof canvas.configureHighDynamicRange,
            // RGBA16F backbuffer renderability is gated on this extension —
            // run-5 forgot it and read INVALID_ENUM.
            colorBufferFloat: !!gl.getExtension("EXT_color_buffer_float"),
          };
          if (out.webgl.drawingBufferStorage) {
            try {
              gl.drawingBufferStorage(gl.RGBA16F, 64, 64);
              out.webgl.drawingBufferFormatAfter =
                "drawingBufferFormat" in gl ? gl.drawingBufferFormat : null;
              // 0x881A = RGBA16F — the call only counts if the format took.
              out.webgl.storageSet =
                out.webgl.drawingBufferFormatAfter === 0x881a ? "ok" : "rejected (format unchanged)";
              gl.clearColor(4.0, 2.0, 1.0, 1.0);
              gl.clear(gl.COLOR_BUFFER_BIT);
              const px = new Float32Array(4);
              gl.readPixels(0, 0, 1, 1, gl.RGBA, gl.FLOAT, px);
              out.webgl.glError = gl.getError();
              out.webgl.backbufferPixel = Array.from(px);
            } catch (e) {
              out.webgl.storageSet = "threw: " + String(e);
            }
          }
        }
        canvas.remove();

        // --- 2D canvas: P4 showed getContextAttributes() exposes
        // toneMapping for float16 2D contexts — can it be set to extended?
        try {
          const c2 = document.createElement("canvas");
          c2.width = 8;
          c2.height = 8;
          const ctx = c2.getContext("2d", {
            colorType: "float16",
            toneMapping: { mode: "extended" },
          });
          out.canvas2d = {
            attrs: ctx.getContextAttributes ? ctx.getContextAttributes() : null,
          };
        } catch (e) {
          out.canvas2d = { error: String(e) };
        }

        done(out);
      })().catch((e) => done({ fatal: String((e && e.stack) || e) }));
    });

    console.log("\n[P5b] ===== WebGL / 2D-canvas HDR surface APIs =====");
    if (r.fatal) {
      console.log("[P5b] FATAL:", r.fatal);
    } else {
      console.log("[P5b] webgl2:", JSON.stringify(r.webgl));
      console.log("[P5b] canvas2d:", JSON.stringify(r.canvas2d));
      const glExtended =
        r.webgl?.ctxAttrsToneMapping?.mode === "extended" ||
        r.webgl?.drawingBufferToneMapping === "function" ||
        r.webgl?.configureHighDynamicRange === "function";
      const c2dExtended = r.canvas2d?.attrs?.toneMapping?.mode === "extended";
      console.log(
        `[P5b] verdict: WebGL extended-range presentation ${glExtended ? "✅ requestable" : "❌ NO shipped control"}; ` +
          `2D-canvas extended ${c2dExtended ? "✅ requestable" : "❌ silently downgraded"}; ` +
          `float16 BACKBUFFER via drawingBufferStorage: ${r.webgl?.storageSet === "ok" ? "✅" : "❌ " + (r.webgl?.storageSet ?? "n/a")}`,
      );
    }
    expect(r.fatal).toBeUndefined();
  });

  it("P5 — HDR glass detection (programmatic half)", async function () {
    this.timeout(60000);
    const r = await browser.executeAsync((done) => {
      (async () => {
        const out = {
          ua: navigator.userAgent,
          matchMedia: {
            dynamicRangeHigh: matchMedia("(dynamic-range: high)").matches,
            videoDynamicRangeHigh: matchMedia("(video-dynamic-range: high)").matches,
            colorGamutP3: matchMedia("(color-gamut: p3)").matches,
            colorGamutRec2020: matchMedia("(color-gamut: rec2020)").matches,
          },
          preferredCanvasFormat: navigator.gpu?.getPreferredCanvasFormat?.() ?? null,
          screenHdrHeadroom:
            typeof screen !== "undefined" && "highDynamicRangeHeadroom" in screen
              ? screen.highDynamicRangeHeadroom
              : null,
        };
        const adapter = await navigator.gpu.requestAdapter();
        const device = await adapter.requestDevice();
        // A real attached canvas (not Offscreen) — closest to actual glass
        // short of a visual check.
        const canvas = document.createElement("canvas");
        canvas.width = 64;
        canvas.height = 64;
        canvas.style.cssText = "position:fixed;left:-9999px;top:0";
        document.body.appendChild(canvas);
        const ctx = canvas.getContext("webgpu");
        try {
          ctx.configure({
            device,
            format: "rgba16float",
            toneMapping: { mode: "extended" },
            alphaMode: "premultiplied",
            usage: GPUTextureUsage.RENDER_ATTACHMENT | GPUTextureUsage.COPY_SRC,
          });
          out.configureExtended = "ok";
        } catch (e) {
          out.configureExtended = "threw: " + String(e);
        }
        try {
          const cfg = ctx.getConfiguration ? ctx.getConfiguration() : null;
          out.getConfiguration = cfg
            ? { format: cfg.format, toneMappingMode: cfg.toneMapping?.mode ?? null }
            : null;
        } catch (e) {
          out.getConfiguration = "threw: " + String(e);
        }
        if (out.configureExtended === "ok") {
          // Write 4.0 into the swap texture and read it back: proves the
          // canvas SURFACE stores extended-range values (presentation to
          // actual HDR glass still needs the visual check).
          try {
            const tex = ctx.getCurrentTexture();
            const enc = device.createCommandEncoder();
            const pass = enc.beginRenderPass({
              colorAttachments: [
                {
                  view: tex.createView(),
                  loadOp: "clear",
                  storeOp: "store",
                  clearValue: { r: 4.0, g: 2.0, b: 1.0, a: 1 },
                },
              ],
            });
            pass.end();
            const rb = device.createBuffer({
              size: 256 * 64,
              usage: GPUBufferUsage.COPY_DST | GPUBufferUsage.MAP_READ,
            });
            enc.copyTextureToBuffer(
              { texture: tex },
              { buffer: rb, bytesPerRow: 256, rowsPerImage: 64 },
              [16, 64, 1],
            );
            device.queue.submit([enc.finish()]);
            await rb.mapAsync(GPUMapMode.READ);
            const u16 = new Uint16Array(rb.getMappedRange());
            const f16 = (h) => {
              const s = h & 0x8000 ? -1 : 1;
              const e = (h >> 10) & 0x1f;
              const m = h & 0x3ff;
              if (e === 0) return s * m * 2 ** -24;
              if (e === 31) return m ? NaN : s * Infinity;
              return s * (1 + m / 1024) * 2 ** (e - 15);
            };
            out.swapchainPixel = { r: f16(u16[0]), g: f16(u16[1]), b: f16(u16[2]) };
            rb.unmap();
          } catch (e) {
            out.swapchainReadbackError = String(e);
          }
        }
        canvas.remove();
        done(out);
      })().catch((e) => done({ fatal: String((e && e.stack) || e) }));
    });

    console.log("\n[P5] ===== HDR glass detection (programmatic) =====");
    if (r.fatal) {
      console.log("[P5] FATAL:", r.fatal);
    } else {
      console.log("[P5] matchMedia:", JSON.stringify(r.matchMedia));
      console.log(
        `[P5] preferredCanvasFormat=${r.preferredCanvasFormat} screenHdrHeadroom=${r.screenHdrHeadroom}`,
      );
      console.log(
        `[P5] configure(rgba16float + toneMapping extended): ${r.configureExtended} echo=${JSON.stringify(r.getConfiguration)}`,
      );
      if (r.swapchainPixel)
        console.log(
          `[P5] swapchain stores extended values: ${JSON.stringify(r.swapchainPixel)} ${
            r.swapchainPixel.r > 1.5 ? "✅ (>1.0 retained)" : "❌ (clamped)"
          }`,
        );
      if (r.swapchainReadbackError)
        console.log("[P5] swapchain readback ERROR:", r.swapchainReadbackError);
      console.log(
        "[P5] NOTE: presentation to real HDR glass needs HDR-mode Windows + an HDR display — visual half not covered here.",
      );
    }
    expect(r.fatal).toBeUndefined();
  });
});
