import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { existsSync, mkdirSync, rmSync } from "node:fs";
import { analyze } from "../lib/analyze.mjs";

const MEDIA_DIR =
  process.env.WEFTCUT_TEST_MEDIA ||
  path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "fixtures", "media");
const PROJECT_PARENT = path.resolve(os.tmpdir(), "weftcut-e2e-audio-proj");

// Audio conformance across the matrix: source frame rate (video-grid-vs-audio
// sync) x export container (mux path). Each case imports the matching audio
// source (per-second tone markers F_k = 400 + 120k Hz), exports to the target
// container, and verifies per-second alignment + A/V drift + tone SNR via
// `media_conformance --audio`. Fixtures are generated by onPrepare.
const FPS = [30, 60, 120];
const CONTAINERS = ["mp4", "mkv", "mov"];
const CASES = FPS.flatMap((fps) => CONTAINERS.map((container) => ({ fps, container })));

describe("audio conformance matrix (real WebView2)", function () {
  before(function () {
    mkdirSync(PROJECT_PARENT, { recursive: true });
  });

  for (const c of CASES) {
    const source = path.resolve(MEDIA_DIR, `test_1080p_${c.fps}fps_audio.mp4`);
    const output = path.resolve(os.tmpdir(), `weftcut-e2e-audio-${c.fps}-${c.container}.${c.container}`);

    it(`${c.fps}fps source -> ${c.container} export stays aligned + synced + faithful`, async function () {
      if (!existsSync(source)) {
        console.warn(`[e2e] SKIP: audio source not found at ${source}`);
        this.skip();
      }
      rmSync(output, { force: true });

      await browser.waitUntil(
        async () =>
          (await browser.execute(
            () => typeof window.__weftcutTest?.newProjectAndEnter === "function",
          )) === true,
        { timeout: 30000, timeoutMsg: "newProjectAndEnter never mounted" },
      );
      const r1 = await browser.executeAsync((parent, done) => {
        window.__weftcutTest
          .newProjectAndEnter({
            parentFolder: parent,
            name: "e2e-audio-" + Date.now(),
            canvas: { width: 1920, height: 1080, fpsNum: 30, fpsDen: 1 },
          })
          .then(() => done({ ok: true }))
          .catch((e) => done({ ok: false, error: String(e) }));
      }, PROJECT_PARENT);
      if (!r1.ok) throw new Error("newProjectAndEnter failed: " + r1.error);

      await browser.waitUntil(
        async () =>
          (await browser.execute(
            () => typeof window.__weftcutTest?.exportClip === "function",
          )) === true,
        { timeout: 30000, timeoutMsg: "exportClip never mounted" },
      );

      await browser.execute(
        (media, out, container) => {
          window.__e2eExportDone = null;
          window.__weftcutTest
            .exportClip({ mediaAbsPath: media, outputAbsPath: out, settings: { container } })
            .then(() => { window.__e2eExportDone = { ok: true }; })
            .catch((e) => { window.__e2eExportDone = { ok: false, error: String(e) }; });
        },
        source,
        output,
        c.container,
      );

      let lastFrame = -1;
      let settled = null;
      try {
        await browser.waitUntil(
          async () => {
            const snap = await browser.execute(() => {
              const st = window.__weftcutExportState;
              return { done: window.__e2eExportDone, kind: st?.kind ?? null, frame: st?.progress?.frame ?? null };
            });
            if (snap.frame != null && snap.frame !== lastFrame) {
              lastFrame = snap.frame;
            }
            if (snap.done) { settled = snap.done; return true; }
            return false;
          },
          { timeout: 170000, interval: 1000 },
        );
      } catch (e) {
        throw new Error(`export never settled (last frame=${lastFrame}): ${e.message}`);
      }
      if (!settled.ok) throw new Error("exportClip failed: " + settled.error);

      const report = analyze({ output, source, samples: [0], audio: true });
      console.log(`[e2e] audio report ${c.fps}fps/${c.container}:`, JSON.stringify(report));

      const misaligned = report.samples.filter((s) => !s.aligned);
      if (misaligned.length > 0) {
        throw new Error("audio seconds misaligned: " +
          JSON.stringify(misaligned.map((s) => ({ second: s.second, detected: s.detected_freq }))));
      }
      expect(Math.abs(report.drift_slope - 1)).toBeLessThanOrEqual(0.01);
      expect(Math.abs(report.offset_ms)).toBeLessThanOrEqual(66);
      expect(report.pass).toBe(true);
    });
  }
});
